### ISSUE TITLE
Any chance for vertical & horizontal options with responsive steps on the wizard?

### ISSUE THREAD

**Issue by arivera12** [xaksis/vue-good-wizard#2] opened 2017-08-22 14:21 UTC
It would be great to have a prop called something like 

**stepsOrientation**: '**vertical|horizontal**'

If you have more than 5 steps then it would be great to have the steps vertically.

Thanks again for this amazing plugin!

**Comment by pimboden** [comment] 2017-09-07 14:55
Nice Component.. and worked !
 Any chance to make it responsive?

**Comment by arivera12** [comment] 2017-09-08 23:51
@pimboden the wizard its already responsive but in very small screen like phones it needs a little workout but not too much make it work smoothly. It just need to draw the wizard step line vertically and connect the icons and that should be all we need. Did you see the behavior of this wizard on small screens? Icons still get arranged perfectly but the step line still going horizontally.

**Comment by pimboden** [comment] 2017-09-12 12:26
Yes, you are right. this looks pretty good most of the times. The issue is if (like in my current use case) you have steps, that have e bit longer names, then the names overlap and are unreadable

**Comment by arivera12** [comment] 2017-09-12 14:29
@pimboden You should try to use concise names on the wizard titles to work around that. I myself sometime need to do this types of workaround to make it look OK. In the meantime we should try to apply some custom css styling to force the wizard icons to split themselves to one per line and align them on the center of the screen. If I find any workaround to make it look good on mobile devices I will paste it here.

**Comment by pimboden** [comment] 2017-09-14 09:49
OK thanks. The problem of the name of the steps, is that they are given by some other Autors.  I'm also trying to tweak around with css.

**Comment by xaksis** [comment] 2018-08-04 00:50
the wizard now has a responsive treatment. going to close this

**Closed by xaksis** 2018-08-04 00:50 UTC
